### ISSUE TITLE
Linux aarch64 rpm won't install

### ISSUE THREAD

**Issue by griffint61** [MuhammedKalkan/OpenLens#103]
Trying to install the aarch64 rpm on AlmaLinux 9.1 (arm edition) gives this error:

```
Error: 
 Problem: conflicting requests
  - package open-lens-6.3.0-1.arm64 does not have a compatible architecture
(try to add '--skip-broken' to skip uninstallable packages or '--nobest' to use not only best candidate packages)
```
I tried the three most recent builds, include 6.4.0-alpha.2

**Comment by griffint61** [comment]
I tried beta.12. The error is:
```
Error: 
 Problem: conflicting requests
  - package open-lens-6.4.0_beta.12-1.arm64 does not have a compatible architecture
```

**Comment by MuhammedKalkan** [comment]
try 6.4.0 release

**Comment by griffint61** [comment]
Same error as before.

I was able to repair the rpm using the `rpmrebuild` utility as follows:

* Command: `rpmrebuild -enp OpenLens-6.4.0.aarch64.rpm`
* I changed these two lines to replace "arm64" with "aarch64".
```
#ARCH:         arm64
BuildArch:     arm64
```
* Saved and exited.
* Answered 'y' to the question for continuing.
* Waited for the rebuild to complete. Result was saved as `~/rpmbuild/RPMS/aarch64/open-lines-6.4.0-1.aarch64.rpm`
* I was able to install that rpm without errors.

This was on done with AlmaLinux 9.1 system running on arm64.

**Comment by griffint61** [comment]
The "repaired" RPM doesn't actually work. During startup the error is:

```
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/index.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js
- /opt/OpenLens/resources/app.asar/static/build/main.js
- 
```
I think what it really wants is `../build/Release/pty.node`, which does actually exist.

**Comment by jkroepke** [comment]
If `../build/Release/pty.node` is there, what about `ldd ../build/Release/pty.node`

**Comment by griffint61** [comment]
File `pty.node` exists under the Release directory.

`ldd` says it is "not a dynamic executable".

`file` says it is  an "ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked"

So it looks to be the wrong architecture. It should be ARM 64. That would explain it.

I found the Release error later in the output. The way the try/catch is structured in `UnixTerminal.ts`, it reports out the Debug error (`innerError`) before reporting the Release error (`outerError`). Anyway the Release error is:

```
Error: /opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node: cannot open shared object file: No such file or directory
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
```

**Comment by jkroepke** [comment]
Hi,

i guess there are multiple errors here...

Maybe the arm64 vs aarch64 mismatch, it seems like an upstream error. Lens is using electron-builder to build rpm.

Here is a condition for if rpm, then aarch64: https://github.com/electron-userland/electron-builder/blob/f6944a3c123f0cee050cbd481cb0916ea46de46f/packages/builder-util/src/arch.ts#L79-L81

but some line above, an additional check for rpm is missing:

https://github.com/electron-userland/electron-builder/blob/f6944a3c123f0cee050cbd481cb0916ea46de46f/packages/builder-util/src/arch.ts#L19-L20

Maybe also is result into additional error. But this is an error, that we can not fix and even the Lens upstream project is not able to resolve the issue. It needs to be reported here: https://github.com/electron-userland/electron-builder

**Comment by jkroepke** [comment]
@griffint61 The bug seems fixed upstream now. I guess it needs to released first in electron-builder and the new release needs to be included in Lens.

Thats everything what we can provide here.

**Comment by dhaluza** [comment]
A similar error is present in the arm64.deb package. please fix it.
`open-lens
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/index.js
- /opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js
- /opt/OpenLens/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js',
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/index.js',
    '/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/static/build/library/main.js',
    '/opt/OpenLens/resources/app.asar/static/build/main.js',
    undefined
  ]
}
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /opt/OpenLens/resources/app.asar.unpacked/node_modules/@k8slens/core/node_modules/node-pty/build/Release/pty.node: Ð½ÐµÐ²Ð¾Ð·Ð¼Ð¾Ð¶Ð½Ð¾ Ð¾ÑÐºÑÑÑÑ ÑÐ°Ð·Ð´ÐµÐ»ÑÐµÐ¼ÑÐ¹ Ð¾Ð±ÑÐµÐºÑÐ½ÑÐ¹ Ñ
                                      Ð°Ð¹Ð»: Ð ÑÐ°ÐºÐ¾Ð³Ð¾ Ñ
                                                             Ð°Ð¹Ð»Ð° Ð¸Ð»Ð¸ ÐºÐ°ÑÐ°Ð»Ð¾Ð³Ð°
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/opt/OpenLens/resources/app.asar/node_modules/@k8slens/core/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
`

**Comment by jkroepke** [comment]
@dhaluza thanks for sharing this, we not able to fix this.

**Comment by jkroepke** [comment]
Checkout the new 9.5 version, maybe its fixed.
