### ISSUE TITLE
Missing latest-mac.yml

### ISSUE THREAD

**Issue by ckosmowski** [MuhammedKalkan/OpenLens#137]
I'm opening this issue here because i guess it has to do with the OpenLens repository.

Currently i can't get my OpenLens to work. When trying to connect to clusters it is endlessly displaying "Connecting". In the logs i found this issue:

```
error: [UPDATE-APP/CHECK-FOR-UPDATES] Cannot find channel "latest-mac.yml" update info: HttpError: 404
"method: GET url: https://github.com/MuhammedKalkan/OpenLens/releases/download/Latest/latest-mac.yml?noCache=1grnfaa1c\n\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\n"
Headers: {
  "server": "GitHub.com",
  "date": "Fri, 17 Mar 2023 09:44:49 GMT",
  "content-type": "text/plain; charset=utf-8",
  "vary": "X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With",
  "cache-control": "no-cache",
  "strict-transport-security": "max-age=31536000; includeSubdomains; preload",
  "x-frame-options": "deny",
  "x-content-type-options": "nosniff",
  "x-xss-protection": "0",
  "referrer-policy": "no-referrer-when-downgrade",
  "content-security-policy": "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'",
  "content-encoding": "gzip",
  "content-length": "29",
  "x-github-request-id": "C52D:13EF6:2B81F:2CA8F:64143691"
}
    at createHttpError (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)
    at ElectronHttpExecutor.handleResponse (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)
    at ClientRequest.<anonymous> (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)
    at ClientRequest.emit (node:events:526:28)
    at ClientRequest.emit (node:domain:475:12)
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)
    at SimpleURLLoaderWrapper.emit (node:events:526:28)
    at SimpleURLLoaderWrapper.emit (node:domain:475:12) {"code":"ERR_UPDATER_CHANNEL_FILE_NOT_FOUND","stack":"Error: Cannot find channel \"latest-mac.yml\" update info: HttpError: 404 \n\"method: GET url: https://github.com/MuhammedKalkan/OpenLens/releases/download/Latest/latest-mac.yml?noCache=1grnfaa1c\\n\\nPlease double check that your authentication token is correct. Due to security reasons, actual status maybe not reported, but 404.\\n\"\nHeaders: {\n  \"server\": \"GitHub.com\",\n  \"date\": \"Fri, 17 Mar 2023 09:44:49 GMT\",\n  \"content-type\": \"text/plain; charset=utf-8\",\n  \"vary\": \"X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With\",\n  \"cache-control\": \"no-cache\",\n  \"strict-transport-security\": \"max-age=31536000; includeSubdomains; preload\",\n  \"x-frame-options\": \"deny\",\n  \"x-content-type-options\": \"nosniff\",\n  \"x-xss-protection\": \"0\",\n  \"referrer-policy\": \"no-referrer-when-downgrade\",\n  \"content-security-policy\": \"default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'\",\n  \"content-encoding\": \"gzip\",\n  \"content-length\": \"29\",\n  \"x-github-request-id\": \"C52D:13EF6:2B81F:2CA8F:64143691\"\n}\n    at createHttpError (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:14:12)\n    at ElectronHttpExecutor.handleResponse (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:116:20)\n    at ClientRequest.<anonymous> (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:82:26)\n    at ClientRequest.emit (node:events:526:28)\n    at ClientRequest.emit (node:domain:475:12)\n    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:6917)\n    at SimpleURLLoaderWrapper.emit (node:events:526:28)\n    at SimpleURLLoaderWrapper.emit (node:domain:475:12)\n    at Object.newError (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:47:19)\n    at GenericProvider.getLatestVersion (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GenericProvider.js:27:50)\n    at async MacUpdater.getUpdateInfoAndProvider (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:298:19)\n    at async MacUpdater.doCheckForUpdates (/Applications/OpenLens.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:312:24)\n    at async /Applications/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:1:298176\n    at async r (/Applications/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:1:299732)\n    at async /Applications/OpenLens.app/Contents/Resources/app.asar/static/build/main.js:1:300493"}
```

**Comment by MuhammedKalkan** [comment]
Latest is alpha so have no yml file. But it shouldnt have anything to do with your nor connecting issue
