### ISSUE TITLE
GLibc version error on Amazon Linux 2

### ISSUE THREAD

**Issue by colorchestra** [MuhammedKalkan/OpenLens#50]
Hi,

on Amazon Linux 2 (which is closely related to CentOS 7 and shares most of its package versions) I can't get the AppImage version of OpenLens to work, it throws the following error:

```
[redacted@redacted ~]$ /opt/OpenLens.AppImage 
innerError Error: Cannot find module '../build/Debug/pty.node'
Require stack:
- /tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js
- /tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/index.js
- /tmp/.mount_OpenLeuf9S7P/resources/app.asar/static/build/main.js
- 
    at Module._resolveFilename (node:internal/modules/cjs/loader:940:15)
    at n._resolveFilename (node:electron/js2c/browser_init:245:1105)
    at Module._load (node:internal/modules/cjs/loader:785:27)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:30:15)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:988:32) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js',
    '/tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/index.js',
    '/tmp/.mount_OpenLeuf9S7P/resources/app.asar/static/build/main.js',
    undefined
  ]
}
(node:18882) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `open-lens --trace-deprecation ...` to show where the warning was created)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib64/libc.so.6: version `GLIBC_2.28' not found (required by /tmp/.org.chromium.Chromium.U8mC8o)
    at process.func [as dlopen] (node:electron/js2c/asar_bundle:5:1812)
    at Module._extensions..node (node:internal/modules/cjs/loader:1203:18)
    at Object.func [as .node] (node:electron/js2c/asar_bundle:5:2039)
    at Module.load (node:internal/modules/cjs/loader:988:32)
    at Module._load (node:internal/modules/cjs/loader:829:12)
    at c._load (node:electron/js2c/asar_bundle:5:13343)
    at Module.require (node:internal/modules/cjs/loader:1012:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/tmp/.mount_OpenLeuf9S7P/resources/app.asar/node_modules/node-pty/lib/unixTerminal.js:26:11)
    at Module._compile (node:internal/modules/cjs/loader:1118:14)
[18882:1103/103947.723854:ERROR:object_proxy.cc(623)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.InvalidArgs: No such interface 'org.freedesktop.portal.FileChooser'
[18882:1103/103947.723997:ERROR:select_file_dialog_linux_portal.cc(242)] Failed to read portal version property
[19162:1103/103948.077148:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[19181:1103/103948.276636:ERROR:viz_main_impl.cc(186)] Exiting GPU process due to errors during initialization
[19196:1103/103948.412883:ERROR:gpu_memory_buffer_support_x11.cc(44)] dri3 extension not supported.
```

the "official" Lens AppImage build works. Can I do something about this or do I need a system with a newer GLibc?

Thank you!

**Comment by MuhammedKalkan** [comment]
You need newer version.
