### ISSUE TITLE
OpenLens v6.3.0 Linux AppImage not opening

### ISSUE THREAD

**Issue by XargonWan** [MuhammedKalkan/OpenLens#84]
It says that it's not a valid binary file.

**Comment by micromachine** [comment]
Howdy, maybe this will help a little bit more. Ubuntu Focal, package OpenLens-6.3.0.amd64.deb  
``` 
greg@obelix:~/.config$ /usr/bin/open-lens

info:    ▪ 🔌 Starting LensProxy +0ms
info:    ▪ [LENS-PROXY]: Proxy server has started at 127.0.0.1:33755 +17ms
info:    ▪ 🔎 Testing LensProxy connection ... +1ms
info:    ▪ [LENS-USER-STORE]: LOADING ... +17ms
info:    ▪ [LENS-USER-STORE]: LOADED from /home/greg/.config/OpenLens/lens-user-store.json +29ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADING ... +1ms
info:    ▪ [LENS-CLUSTER-STORE]: LOADED from /home/greg/.config/OpenLens/lens-cluster-store.json +5ms
info:    ▪ ⚡ LensProxy connection OK +52ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Loading content for window "splash" from file: /opt/OpenLens/resources/app.asar/static/splash.html... +166ms
info:    ▪ [CREATE-ELECTRON-WINDOW]: Window "splash" loaded +2s
info:    ▪ [LENS-EXTENSIONS]: LOADING ... +29ms
info:    ▪ [LENS-EXTENSIONS]: LOADED from /home/greg/.config/OpenLens/lens-extensions.json +24ms
info:    ▪ [LENS-WEBLINK-STORE]: LOADING ... +40ms
info:    ▪ [LENS-WEBLINK-STORE]: LOADED from /home/greg/.config/OpenLens/lens-weblink-store.json +45ms
info:    ▪ 📟 Setting protocol client for lens:// +48ms
info:    ▪ 📟 Protocol client register failed ❗ +75ms
info:    ▪ 🧩 Initializing extensions +5ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADING ... +74ms
info:    ▪ [LENS-FILESYSTEM-PROVISIONER-STORE]: LOADED from /home/greg/.config/OpenLens/lens-filesystem-provisioner-store.json +4ms
info:    ▪ 🐚 Syncing shell environment +2ms
info:    ┏ [UNIX-SHELL-ENV]: running against  +6ms
info:    ┃ [1] {
info:    ┃ [2]   command: ` '/opt/OpenLens/open-lens' -p '"fab0445547a248b88858e3d1751e041e" + JSON.stringify(process.env) + "fab0445547a248b88858e3d1751e041e"'`,
info:    ┃ [3]   shellArgs: [ '-l', '-i' ]
info:    ┗ [4] }
info:    ▪ [EXTENSIONS-LOADER]: auto initializing extensions +143ms
info:    ▪ [LENS-HOTBAR-STORE]: LOADING ... +7ms
info:    ▪ [LENS-HOTBAR-STORE]: LOADED from /home/greg/.config/OpenLens/lens-hotbar-store.json +6ms
APPIMAGE env is not defined, current application is not an AppImage
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'file' cannot be empty. Received ''
    at new NodeError (node:internal/errors:371:5)
    at normalizeSpawnArguments (node:child_process:517:11)
    at spawn (node:child_process:702:13)
    at /opt/OpenLens/resources/app.asar/static/build/main.js:2:428162
    at new Promise (<anonymous>)
    at /opt/OpenLens/resources/app.asar/static/build/main.js:2:428137
    at /opt/OpenLens/resources/app.asar/static/build/main.js:2:426687
    at Object.run (/opt/OpenLens/resources/app.asar/static/build/main.js:2:430284)
    at /opt/OpenLens/resources/app.asar/static/build/main.js:2:314571
    at Array.map (<anonymous>) {
  code: 'ERR_INVALID_ARG_VALUE'
}
info:    ▪ [EXTENSION-DISCOVERY] loading extensions from /home/greg/.config/OpenLens +57ms
APPIMAGE env is not defined, current application is not an AppImage

```

**Comment by MuhammedKalkan** [comment]
See 6.4.0 and open new if still exists
